services:
  apollo-server-dashboard:
    build:
      context: .
    container_name: apollo-server-dashboard
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped
    depends_on:
      - apollo-server-dashboard-backend
    networks:
      - apollo-server-network

  apollo-server-dashboard-backend:
    build:
      context: ./backend
    container_name: apollo-server-dashboard-backend
    environment:
      - API_KEY=${API_KEY}
      - FREE_GAMES_NOTIFIER_URL=${FREE_GAMES_NOTIFIER_URL:-http://free-games-notifier:8000}
      - FREE_GAMES_NOTIFIER_API_KEY=${FREE_GAMES_NOTIFIER_API_KEY}
      - FREE_GAMES_NOTIFIER_TEST_WEBHOOK_URL=${FREE_GAMES_NOTIFIER_TEST_WEBHOOK_URL}
    restart: unless-stopped
    networks:
      - apollo-server-network

networks:
  apollo-server-network:
    external: true
