services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - apollo-server-dashboard-backend

  apollo-server-dashboard-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SERVICES_CONFIG: /app/config/services.yaml
    volumes:
      - ./config:/app/config
    expose:
      - "8001"
