import { 
    Bell, 
    BellRing,
    RefreshCw, 
    Play, 
    Square, 
    RotateCcw, 
    Terminal, 
    Globe, 
    Settings, 
    AlertTriangle,
    Send,
    SendHorizontal,
    Pickaxe, 
    Loader,
    CircleAlert,
    PackageOpen,
    LayoutDashboard,
    FolderGit2,
    ShieldCheck,
    ShieldCog,
    ExternalLink,
    Container,
    Activity,
    Home,
    Cloud,
    Server,
    BarChart2,
    GitBranch,
    Bookmark,
    Zap,
    Network,
} from "lucide-react"

const icons = {
    "bell": Bell,
    "bell-ring": BellRing,
    "refresh": RefreshCw,
    "play": Play,
    "stop": Square,
    "restart": RotateCcw,
    "terminal": Terminal,
    "globe": Globe,
    "settings": Settings,
    "alert": AlertTriangle,
    "send": Send,
    "send-horizontal": SendHorizontal,
    "pickaxe": Pickaxe,
    "loader": Loader,
    "error": CircleAlert,
    "empty": PackageOpen,
    "dashboard": LayoutDashboard,
    "github": FolderGit2,
    "shield-check": ShieldCheck,
    "shield-cog": ShieldCog,
    "external-link": ExternalLink,
    "container": Container,
    "activity": Activity,
    "home": Home,
    "cloud": Cloud,
    "server": Server,
    "bar-chart": BarChart2,
    "git-branch": GitBranch,
    "bookmark": Bookmark,
    "zap": Zap,
    "network": Network,
}

export function getIcon(name, props = {}) {
    const Icon = icons[name]
    if (!Icon) return null
    return <Icon size={16} {...props} />
}